export const ACTION_TYPES = {
    SET_THEME:"SET_THEME",
    ADD_BLOG:"ADD_BLOG",
    UPDATE_BLOGS:"UPDATE_BLOGS",
    SET_ACTIVE_BLOG: "SET_ACTIVE_BLOG",
    BLOGS_INIT:"BLOGS_INIT",
    UPDATE_ACTIVE_BLOG:"UPDATE_ACTIVE_BLOG",
    SEARCH_BLOGS:"SEARCH_BLOGS",
    FILTER_INIT:"FILTER_INIT",
    UPDATE_FILTER:"UPDATE_FILTER",
    ADD_FILTER:"ADD_FILTER"
}