export const LIKE_MOVIE = "LIKE_MOVIE";
export const SELECT_MOVIE = "SELECT_MOVIE";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const UPDATE_LIKE_COUNT = "UPDATE_LIKE_COUNT ";
